name: Vibifiy App Dispatcher

on:
  push:
    branches:
      - main
    paths:
      - 'VibiPass/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-vibipass:
    name: Build VibiPass
    uses: ./.github/workflows/build.yml
    permissions:
      contents: write
